{{- if and .Values.configmap.enabled .Values.configmap.data }}

apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ default (printf "%s-config" (include "shopverse-backend.fullname" .)) .Values.configmap.name }}

  labels:
    {{- include "shopverse-backend.labels" . | nindent 4 }}

data:
  {{- toYaml .Values.configmap.data | nindent 2 }}

{{- end }}
