namespace: shopverse-dev
# ──────────────────────────────────────
# BACKEND
# ──────────────────────────────────────
image:
  uri: 254405569649.dkr.ecr.us-east-1.amazonaws.com
  name: shopverse/backend # shopverse-backend
  version: v1
  digest: sha256:a30081ea8b33d014bb1ae9af01f2498ec1963121cf4899882351e9816e9fb8ba
deployment:
  name: backend-deploy
  replicas: 1
service:
  name: backend-svc
  port: 8080
  targetPort: 8080
configmap:
  name: backend-config
secret:
  name: shopverse-dev-mysql-jwt-credentials
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
# ──────────────────────────────────────
# MySQL
# ──────────────────────────────────────
mysql:
  host: shopverse-dev-mysql.ca9aykaigakf.us-east-1.rds.amazonaws.com
  port: 3306
  externalNameService: shopverse-mysql-ens
  database: shopverse
  user: shopverse
jwtSecret: ""
