apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "shopverse-frontend.fullname" . }}
  labels:
    {{- include "shopverse-frontend.labels" . | nindent 4 }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "shopverse-frontend.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "shopverse-frontend.selectorLabels" . | nindent 8 }}

      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    spec:

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "shopverse-frontend.serviceAccountName" . }}

      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        {{- toYaml .Values.podSecurityContext.values | nindent 8 }}
      {{- end }}

      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}

      containers:
        - name: {{ .Values.containerName }}

          image: "{{ include "shopverse-frontend.image" . }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          {{- if .Values.containerSecurityContext.enabled }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext.values | nindent 12 }}
          {{- end }}

          {{- if and .Values.envFrom.enabled .Values.envFrom.values }}
          envFrom:
            {{- toYaml .Values.envFrom.values | nindent 12 }}
          {{- end }}

          {{- if and .Values.env.enabled .Values.env.values }}
          env:
            {{- toYaml .Values.env.values | nindent 12 }}
          {{- end }}

          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.values | nindent 12 }}
          {{- end }}

          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            {{- toYaml .Values.startupProbe.values | nindent 12 }}
          {{- end }}

          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.values | nindent 12 }}
          {{- end }}

          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe.values | nindent 12 }}
          {{- end }}
