{{- if .Values.service.enabled }}

apiVersion: v1
kind: Service

metadata:
  name: {{ include "shopverse-frontend.fullname" . }}
  labels:
    {{- include "shopverse-frontend.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}

  selector:
    {{- include "shopverse-frontend.selectorLabels" . | nindent 4 }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP

{{- end }}
