name: GitOps CI - Helm + Kubernetes Security

on:
  pull_request:
    branches:
      - main
    paths:
      # - 'charts/**'
      - 'envs/**'
      - '.github/workflows/ci-gitops.yml'
      - '.github/workflows/_reusable-pr-gitops.yml'

permissions:
  contents: read
  pull-requests: read
  security-events: write


jobs:

  # ============================================================
  # 1. Find changed values files
  # ============================================================

  Detect-Changes-Job:
    name: Detect GitOps Changes
    runs-on: ubuntu-latest

    outputs:
      component: ${{ steps.detect.outputs.component }}
      environment: ${{ steps.detect.outputs.environment }}
      chart_path: ${{ steps.detect.outputs.chart_path }}
      helm_values_file: ${{ steps.detect.outputs.helm_values_file }}

    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Detect Changes
        id: detect
        shell: bash
        run: |

          set -euo pipefail
          # ----------------------------------------------------------------
          # We only care about files like:
          #
          # envs/dev/values-backend.yaml
          # envs/qa/values-payment.yaml
          # envs/prod/values-order.yaml
          # ----------------------------------------------------------------

          # if [[ "$file" =~ ^envs/([^/]+)/values-([^/]+)\.yaml$ ]]; then

          while read -r file; do

            echo "File changed: $file"
        
            if [[ "$file" =~ ^envs/([^/]+)/values-(.+)\.yaml$ ]]; then
        
                environment="${BASH_REMATCH[1]}"
                component="${BASH_REMATCH[2]}"
        
                chart_path="helm-charts/$environment/$component"
                helm_values_file="$file"
        
                echo "Component   : $component"
                echo "Environment : $environment"
                echo "Chart       : $chart_path"
                echo "Values      : $helm_values_file"
        
                echo "component=$component" >> "$GITHUB_OUTPUT"
                echo "environment=$environment" >> "$GITHUB_OUTPUT"
                echo "chart_path=$chart_path" >> "$GITHUB_OUTPUT"
                echo "helm_values_file=$helm_values_file" >> "$GITHUB_OUTPUT"
        
            fi
        
          done < <(
            git diff --name-only \
              "${{ github.event.pull_request.base.sha }}" \
              "${{ github.event.pull_request.head.sha }}"
          )

  # ============================================================
  # 2. Run reusable validation workflow
  # ============================================================

  GitOps-Validation-Job:
    name: "${{ needs.Detect-Changes-Job.outputs.component }} / ${{ needs.Detect-Changes-Job.outputs.environment }}"
    needs: Detect-Changes-Job
    # if: needs.Detect-Changes.outputs.matrix != '{"include":[]}'
    uses: ./.github/workflows/_reusable-pr-gitops.yml
    with:
      component: ${{ needs.Detect-Changes-Job.outputs.component }}
      environment: ${{ needs.Detect-Changes-Job.outputs.environment }}
      chart-path: ${{ needs.Detect-Changes-Job.outputs.chart_path }}
      values-file: ${{ needs.Detect-Changes-Job.outputs.helm_values_file }}
      
